In [1]:
import torch
import torch.nn as nn

In [2]:
VOCABULARY_SIZE=10
EMBEDDING_DIM=4

In [15]:
BATCH_SIZE=5
SEQ_LEN=3
sequence = torch.randint(low=0, high=VOCABULARY_SIZE, size=(BATCH_SIZE, SEQ_LEN))

In [16]:
sequence

tensor([[6, 2, 8],
        [3, 5, 6],
        [9, 0, 5],
        [1, 2, 9],
        [0, 9, 1]])

In [17]:
embedding = nn.Embedding(num_embeddings=VOCABULARY_SIZE, embedding_dim=EMBEDDING_DIM)

In [22]:
print(embedding.weight)

Parameter containing:
tensor([[-0.5210,  0.5632, -0.6069, -1.4454],
        [-2.3594,  0.5233, -0.1607, -0.7668],
        [ 1.9446,  0.1064, -1.3341,  1.4237],
        [ 0.1139,  0.3790,  2.4349,  0.2668],
        [ 2.7912,  0.8139,  0.6718, -0.0641],
        [ 2.2724, -0.8105, -0.7964,  0.9931],
        [-0.3413,  1.0576,  0.3027, -0.3740],
        [-0.0513, -1.7193,  0.3848, -0.1908],
        [ 1.8881,  2.0898, -0.4592,  0.3180],
        [-0.7114, -0.2068, -0.1184,  0.8716]], requires_grad=True)


In [29]:
with torch.inference_mode():
    embedding(torch.tensor(0))

In [19]:
with torch.inference_mode():
    embeddings = embedding(sequence)
    print(embeddings)

tensor([[[-0.3413,  1.0576,  0.3027, -0.3740],
         [ 1.9446,  0.1064, -1.3341,  1.4237],
         [ 1.8881,  2.0898, -0.4592,  0.3180]],

        [[ 0.1139,  0.3790,  2.4349,  0.2668],
         [ 2.2724, -0.8105, -0.7964,  0.9931],
         [-0.3413,  1.0576,  0.3027, -0.3740]],

        [[-0.7114, -0.2068, -0.1184,  0.8716],
         [-0.5210,  0.5632, -0.6069, -1.4454],
         [ 2.2724, -0.8105, -0.7964,  0.9931]],

        [[-2.3594,  0.5233, -0.1607, -0.7668],
         [ 1.9446,  0.1064, -1.3341,  1.4237],
         [-0.7114, -0.2068, -0.1184,  0.8716]],

        [[-0.5210,  0.5632, -0.6069, -1.4454],
         [-0.7114, -0.2068, -0.1184,  0.8716],
         [-2.3594,  0.5233, -0.1607, -0.7668]]])
