# Random Sampling

In deep leaning we often deal with tensors that contain random varialbes. We need random variables either to generate dummy data to test our models, or to use randomness directly in our models. In this notebook we are only going to learn how to generate random data based on different types of distributions.

In [1]:
import torch

## Distributions

Below we will discuss a subset of PyTorch methods. Primarily we are going to focus on the uniform distribution and the normal distribution. Most of the time time those functions are all that you will require. All of the below methods will require the `size` option to determine the dimensions of the tensor.

### Uniform Distribution

The `torch.rand()` method generates a tensor with random numbers between 0 and 1 (1 is not inclusive).

In [2]:
torch.rand(size=(2,2))

tensor([[0.1414, 0.3196],
        [0.4052, 0.6802]])

The `torch.randint` method generate a tensor that contains random variables from a uniform distribution between `low` and `high`.

In [3]:
torch.randint(low=1, high=10, size=(2, 2))

tensor([[5, 7],
        [9, 1]])

### Normal Distribution

We can either use `torch.randn` to draw from a standard normal distribution or `torch.normal` and provide `mean` and `std` to the method. 

In [4]:
torch.normal(mean=0, std=1, size=(2,2))

tensor([[ 0.3835,  0.9710],
        [-0.7234,  1.9226]])

In [5]:
torch.randn(size=(2,2))

tensor([[ 0.6851, -0.1018],
        [-0.3372,  0.8611]])

## Determinism

The methods that are used for random sampling do not actually produce random variables, but use so called pseudo random generators. The advantage of pseudo random numbers is that they follow the same pattern, given the same initial conditions. In programming that initial number is called `seed`. If we set the same seed, the psuedo random number generator will produce the same numbers. This is especially useful for reproducable results. In PyTorch we use `torch.manual_seed(seed)`.

In [6]:
torch.manual_seed(10)

In [7]:
torch.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [8]:
torch.manual_seed(10)

In [9]:
torch.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])