In [1]:
import torch
import numpy as np

# Tensor Basics in PyTorch

## The Tensor class

All of modern deep learning works with matrices. According to the PyTorch documentation, `torch.Tensor` is a multi-dimensional matrix containing elements of a single data type. This class is at the core of PyTorch and is going to be used throughout all future tutorial series.

## Setting the device

Tensors can live an the `cpu` or the `gpu`. If we have an Nvidia graphics card, we can define gpu as the device. The device variable can be later used to move the tensors between the cpu and the gpu.

In [2]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [3]:
print(device)

cuda:0


If you want to find out if you have an Nvidia graphics card from the terminal, you can run the command `nvidia-smi`.

In [4]:
!nvidia-smi

Sun Jan 16 12:29:47 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.86       Driver Version: 470.86       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P0    25W /  N/A |      8MiB /  5946MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Creating a Tensor

`torch.tensor(data, dtype=None, device=None, requires_grad=False)`

The method `torch.tensor()` is the most straightforward way to create a tensor. 
- The `data` is the input that is transformed into a tensor. Usually it is an arraylike structure: list, tuple, NumPy ndarray. 
- `dtype` tetermines the type of the tensor. See https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype for a full list of available data types.
- `device` determines if the tensor is going to live on cpu or gpu
- `requires_grad` determines if the tensor needs to be included in gradient descent calculations. This will be covered in more detail in future tutorials.

In [5]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=False)

In [6]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


## Accessing and changing Tensor properties

We can access the properties of the tensor by using `my_tensor.data`, `my_tensor.dtype`, `my_tensor.device` and `my_tensor.requires_grad`

In [7]:
my_tensor.data

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [8]:
my_tensor.dtype

torch.float32

In [9]:
my_tensor.device

device(type='cuda', index=0)

In [10]:
my_tensor.requires_grad

False

Sometimes it is necessary to convert a Tensor to a different dtype or to move the Tensor to a different device. We can use `Tensor.to()` to accomplish those tasks. `Tensor.to()` does not change the datatype/device of the original Tensor.

In [11]:
my_tensor.to(dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', dtype=torch.float64)

In [12]:
my_tensor.to(device='cpu')

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
# still has the same datatype and device
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

## Tensor Dimensions

We can use use `my_tensor.size()` or `my_tensor.shape` to find out the dimensions of the tensor.

In [14]:
my_tensor.size()

torch.Size([2, 3])

In [15]:
my_tensor.shape

torch.Size([2, 3])

## Other functions to create a Tensor

`from_numpy()` turns a numpy ndarray into a PyTorch tensor

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [17]:
t = torch.from_numpy(a)

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

`torch.zeros()` returns a Tensor with all zeros, `torch.ones()` returns a Tensor with all ones and `torch.eye()` returns an identity Tensor.

In [20]:
torch.zeros(size=(2, 2))

tensor([[0., 0.],
        [0., 0.]])

In [21]:
torch.ones(size=(2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [22]:
torch.eye(n=2)

tensor([[1., 0.],
        [0., 1.]])

We can also create a Tensor that contains a specified range of values using for example `torch.arange()`, `torch.linspace()` or `torch.logspace()`.

`torch.arange(start=0, end, step=1)` creates a 1-D Tensor. The "end" is non inclusive.

In [23]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

`torch.lispace(start, end, steps)` creates a 1-D Tensor that evenly spaces the "steps" values between "start" and "end" values.

In [24]:
torch.linspace(1, 10, 20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

`torch.logspace(start, end, steps, base=10.0)` spaces "steps" values between "start" and "end" using log scale with the given base.

In [25]:
torch.logspace(1, 10, 20, 10)

tensor([1.0000e+01, 2.9764e+01, 8.8587e+01, 2.6367e+02, 7.8476e+02, 2.3357e+03,
        6.9519e+03, 2.0691e+04, 6.1585e+04, 1.8330e+05, 5.4556e+05, 1.6238e+06,
        4.8329e+06, 1.4384e+07, 4.2813e+07, 1.2743e+08, 3.7927e+08, 1.1288e+09,
        3.3598e+09, 1.0000e+10])