In [1]:
import torch

# PyTorch Operations

In this chapter we will shortly discuss basic operations that you commonly apply to tensors. The `my_tensor` Tensor is going to be used to demonstrate different types of operations.

In [2]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

## Simple Indexing and Slicing

Indexing is the process by which you retrieve subtensors from a tensor.

To retrieve a single value you can access the value by using the following syntax `Tensor[dim1, dim2, dim3 ...]`. Each number specifies a value along a specific dimension. For example `Tensor[1, 2]` retrieves a value at 1st row and 2nd column (indexing is zero based). You  need to specify a number for each available dimension.

In [4]:
# our tensor is of shape (2, 3), it is a two dimensional tensor: a matrix
my_tensor.shape

torch.Size([2, 3])

In [5]:
# The below indexing operation gets the value in the first row and the third column
my_tensor[0, 2]

tensor(3)

We can also apply indexing to retrieve a tensor and not a single value using the slicing operator `:`, `Tensor[start:end, start:end]`. In this operation the start is inclusive and the end is non inclusive. If we do not provide a start, the indexing starts at the first value of the dimension. If we do not provide an end the indexing goes to the very end.

In [6]:
# get the tensor that includes the first row and the second and third column.
my_tensor[0, 1:]

tensor([2, 3])

In [7]:
# select all rows and the second column
my_tensor[:, 1]

tensor([2, 5])

If we have a highly dimensional tensor, we can utilize the Ellipsis operator `...` as a slicing operator. For example `Tensor[..., index1, index2]` would select all values in the dimensions before the last two dimensions. If we had a four dimensional tuple this would correspond to `Tensor[:, :, index1, index2]`.

In [8]:
# the below operation selects all rows and the 2nd column.
my_tensor[..., 1]

tensor([2, 5])

## Indexing by gathering

We can also use the `gather(dim, index)` method to select value from a Tensor by providingg an index Tensor.

In [27]:
my_tensor

tensor([[22,  2,  3],
        [ 4,  5,  6]])

In [28]:
indices = torch.tensor([[0, 1, 0]])
my_tensor.gather(dim=0, index=indices)

tensor([[22,  5,  3]])

## Mutating the Tensor

We can use the assignment operator `=` to change the individual values of the Tensor.

In [9]:
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
my_tensor[0, 0] = 22

In [11]:
my_tensor

tensor([[22,  2,  3],
        [ 4,  5,  6]])

## Changing the shape of the Tensor

In [12]:
my_tensor

tensor([[22,  2,  3],
        [ 4,  5,  6]])

In [13]:
my_tensor.shape

torch.Size([2, 3])

We can use the `Tensor.view()` method to change the dimensions of the Tensor.

In [14]:
# we turn the Tensor from (2,3) to (1, 6)
my_tensor.view(1, 6)

tensor([[22,  2,  3,  4,  5,  6]])

The changing of dimensions needs to make sense. For example there is no way to make a (2,3) shaped vector into a (7, 23) shaped vector. If we tried, we would raise an exception.

In [15]:
# uncomment the code below to raise an error
# my_tensor.view(7, 23)

## Adding and Removing Dimensions

The `squeeze()` and the `unsqueeze()` operations allow us to add and remove dimensions of size 1. If we have a Tensor with the shape `(1, 2, 3, 1)` the `squeeze()` operation will remove the dimensions of size 1 and return a tensor of shape `(2, 3)`. We can also specify the dimension, so that `Tensor.squeeze(dim=0)` will only remove the first dimension. The `unsqueeze(dim=...)` operation does the exact opposite. The operation add an extra dimension of size 1 at a location specified by the parameter `dim`, for example `dim=1`.

In [16]:
my_tensor.size()

torch.Size([2, 3])

In [17]:
new_tensor = my_tensor.unsqueeze(dim=0)

In [18]:
new_tensor

tensor([[[22,  2,  3],
         [ 4,  5,  6]]])

In [19]:
new_tensor.size()

torch.Size([1, 2, 3])

In [20]:
newest_tensor = new_tensor.squeeze()

In [21]:
newest_tensor.size()

torch.Size([2, 3])