# PyTorch Tensors

In [1]:
import torch

All of modern deep learning works with matrices. According to the PyTorch documentation, `torch.Tensor` is a multi-dimensional matrix containing elements of a single data type. This class is at the core of PyTorch and is going to be used throughout all future tutorial series.

Tensors can live an the `cpu` or the `gpu`. To move a tensor to the gpu, we need to have an Nvidia graphics card. We can test if we have a valid graphics card, by running `torch.cuda.is_available()`. If the method returns `True` we move our calculations to the graphics card to speed up calculations. 

Often we want to save the result of `torch.cuda.is_available()` using a `torch.device` object. Later we can reuse that object to automatically move the calculations to the correct device.

In [2]:
# cuda:0 represents the first nvidia device
# theoretically you could have several graphics cars
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

We are dealing with a system that utilizes an nvidia graphics card.

In [3]:
print(device)

cuda:0


If you want to find out if you have an Nvidia graphics card from the terminal, you can run the command `nvidia-smi`.

In [4]:
!nvidia-smi

Mon Jul 25 14:54:32 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P8    10W /  N/A |    851MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

---

The method `torch.tensor()` is the most straightforward way to create a tensor. 

The method has some interesting arguments, that allow us to control the properties of the tensor: `torch.tensor(data, dtype=None, device=None, requires_grad=False)`

The `data` argument is the input that is transformed into a tensor. Usually it is an arraylike structure: list, tuple, NumPy ndarray. If for example we use `torch.tensor(data=[[0,1,2], [3,4,5]])` we would create a two dimensional matrix with 2 rows and 3 columns.

In [5]:
tensor = torch.tensor([[0, 1, 2], [3, 4, 5]])
print(tensor)

tensor([[0, 1, 2],
        [3, 4, 5]])


The `dtype` argument determines the type of the tensor. See [PyTorch Docs](https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype) for a full list of available data types. If we do not specify the type explicitly, `dtype` is going to be `torch.int64`, if all of inputs are integers and `dtype` is going to be `torch.float32` if even one of the inputs is a float.

In [6]:
tensor = torch.tensor([[0, 1, 2], [3, 4, 5]], dtype=torch.float32)
print(tensor.dtype)

torch.float32


The `device` argument determines if the tensor is going to live on cpu or gpu. We can use the `device` variable we determined above.

In [7]:
tensor = torch.tensor([[0, 1, 2], [3, 4, 5]], device=device)
print(tensor.device)

cuda:0


`requires_grad` determines if the tensor needs to be included in gradient descent calculations. This will be covered in more detail in future tutorials.

In [8]:
tensor = torch.tensor([[0, 1, 2], [3, 4, 5]], dtype=torch.float32, device=device, requires_grad=True)
print(tensor.device)

cuda:0


If we need to change the parameters of an already initialized `Tensor`, we can do the adjustments in a later step, primarily using the `to` method of the `Tensor` class. The `to` method does not overwrite the original `Tensor`, but returns an adjusted one.

In [9]:
tensor = torch.tensor([[0, 1, 2], [3, 4, 5]])
print(f'Original Tensor: dtype={tensor.dtype}, device={tensor.device}, requires_grad={tensor.requires_grad}')
tensor = tensor.to(torch.float32)
print(f'Adjusted dtype: dtype={tensor.dtype}, device={tensor.device}, requires_grad={tensor.requires_grad}')
tensor = tensor.to(device)
print(f'Adjusted device: dtype={tensor.dtype}, device={tensor.device}, requires_grad={tensor.requires_grad}')
tensor.requires_grad = True
print(f'Adjusted requres_grad: dtype={tensor.dtype}, device={tensor.device}, requires_grad={tensor.requires_grad}')

Original Tensor: dtype=torch.int64, device=cpu, requires_grad=False
Adjusted dtype: dtype=torch.float32, device=cpu, requires_grad=False
Adjusted device: dtype=torch.float32, device=cuda:0, requires_grad=False
Adjusted requres_grad: dtype=torch.float32, device=cuda:0, requires_grad=True


We can use use `my_tensor.size()` or `my_tensor.shape` to find out the dimensions of the tensor. Our `Tensor` from above has 2 rows and 3 columns. In practice all deep learning framworks expect the first dimension to represent the number of batches.

In [10]:
# In practice that would be a batch of 2 samples with 3 features
print(tensor.size())
print(tensor.shape)

torch.Size([2, 3])
torch.Size([2, 3])


There are many more methods to create a Tensor. The method `torch.from_numpy()` turns a numpy ndarray into a PyTorch tensor,  `torch.zeros()` returns a Tensor with all zeros, and `torch.ones()` returns a Tensor with all ones. We will see more of those methods as we go along. It makes no sense to cover all of them without any context. 

PyTorch, like other frameworks that work with arrays/tensors, is extremely efficient when it comes to matrix operations. These operations are done in parallel and can be transfered to the GPU if you have a cuda compatibale graphics card. We will use two tensors, $\mathbf{A}$ and $\mathbf{B}$ to demonstrate basic mathematical operations.

In [11]:
A = torch.ones(size=(2, 2), dtype=torch.float32)
B = torch.tensor([[1, 2],[3, 4]], dtype=torch.float32)

We can add, subtract, multiply and divide those matrices elementwise using basic mathematic operators like `+, -, *, /`.

In [12]:
print(A + B)
print(A - B)
print(A * B)
print(A / B)

tensor([[2., 3.],
        [4., 5.]])
tensor([[ 0., -1.],
        [-2., -3.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 0.5000],
        [0.3333, 0.2500]])


We can achieve the same using the methods: `Tensor.add(). Tensor.subtract(), Tensor.multiply(), Tensor.divide()`.

In [13]:
print(A.add(B))
print(A.subtract(B))
print(A.multiply(B))
print(A.divide(B))

tensor([[2., 3.],
        [4., 5.]])
tensor([[ 0., -1.],
        [-2., -3.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 0.5000],
        [0.3333, 0.2500]])


While the above methods do not change the original tensors, each of the methods has a corresponding method that changes the tensor in place. These methods always end with `_`: `add_()`, `subtract_()`, `multiply_()`, `divide_()`.

In [14]:
test = torch.tensor([[1, 2], [4, 4]], dtype=torch.float32)
test.add_(A)
# the test tensor was changed
print(test)

tensor([[2., 3.],
        [5., 5.]])


If we want to apply matrix multiplication $ \mathbf{A} \mathbf{B} $ we use the `mathmul` method.

In [15]:
# Equivalent to torch.matmul(A, B)
A.matmul(B)

tensor([[4., 6.],
        [4., 6.]])

Alternatively we can use `@` as a convenient way to use matrix multiplication.

In [16]:
A @ B

tensor([[4., 6.],
        [4., 6.]])

There is a lot more operations and methods that we can apply to tensors. We will utilize them as we move along. We will try to shortly explain those operations when we encounter them the first time, but if you encounter an operation that was not covered, we expect you to either use a search engine or to use the official PyTorch documentation. In practice this is what you will have to do in order to improve.